# Generated by Django 6.0.2 on 2026-02-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueadero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagFechaPago', models.DateTimeField(auto_now_add=True)),
                ('pagMonto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagMetodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=15)),
                ('pagEstado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=10)),
                ('fkIdParqueo', models.ForeignKey(db_column='fkIdParqueo', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='parqueadero.inventarioparqueo')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
            },
        ),
    ]
