# Generated by Django 6.0.2 on 2026-02-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupNombre', models.CharField(max_length=100)),
                ('cupTipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('VALOR_FIJO', 'Valor Fijo')], max_length=10)),
                ('cupValor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cupDescripcion', models.TextField(blank=True)),
                ('cupFechaInicio', models.DateField()),
                ('cupFechaFin', models.DateField()),
                ('cupActivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'db_table': 'cupones',
            },
        ),
        migrations.CreateModel(
            name='CuponAplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoDescontado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fkIdCupon', models.ForeignKey(db_column='fkIdCupon', on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='cupones.cupon')),
                ('fkIdPago', models.ForeignKey(db_column='fkIdPago', on_delete=django.db.models.deletion.CASCADE, related_name='cupones_aplicados', to='pagos.pago')),
            ],
            options={
                'verbose_name': 'Cupón Aplicado',
                'verbose_name_plural': 'Cupones Aplicados',
                'db_table': 'cupones_aplicados',
            },
        ),
    ]
