# Generated by Django 6.0.2 on 2026-02-23 15:08

from django.db import migrations, models


def populate_cupcodigo(apps, schema_editor):
    """Copiar cupNombre a cupCodigo para cupones existentes"""
    Cupon = apps.get_model('cupones', 'Cupon')
    for cupon in Cupon.objects.all():
        cupon.cupCodigo = cupon.cupNombre.upper().replace(' ', '')[:30]
        cupon.save(update_fields=['cupCodigo'])


class Migration(migrations.Migration):

    dependencies = [
        ('cupones', '0001_initial'),
    ]

    operations = [
        # 1. Agregar campo nullable primero
        migrations.AddField(
            model_name='cupon',
            name='cupCodigo',
            field=models.CharField(default='', max_length=30),
        ),
        # 2. Llenar datos existentes
        migrations.RunPython(populate_cupcodigo, migrations.RunPython.noop),
        # 3. Hacer unique
        migrations.AlterField(
            model_name='cupon',
            name='cupCodigo',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
