# Generated by Django 6.0.2 on 2026-02-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pisNombre', models.CharField(max_length=50)),
                ('pisEstado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Piso',
                'verbose_name_plural': 'Pisos',
                'db_table': 'pisos',
            },
        ),
        migrations.CreateModel(
            name='TipoEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Espacio',
                'verbose_name_plural': 'Tipos de Espacio',
                'db_table': 'tipos_espacio',
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espNumero', models.CharField(max_length=20)),
                ('espEstado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=11)),
                ('fkIdPiso', models.ForeignKey(db_column='fkIdPiso', on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='parqueadero.piso')),
                ('fkIdTipoEspacio', models.ForeignKey(db_column='fkIdTipoEspacio', on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='parqueadero.tipoespacio')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'db_table': 'espacios',
            },
        ),
        migrations.CreateModel(
            name='InventarioParqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parHoraEntrada', models.DateTimeField(auto_now_add=True)),
                ('parHoraSalida', models.DateTimeField(blank=True, null=True)),
                ('fkIdEspacio', models.ForeignKey(db_column='fkIdEspacio', on_delete=django.db.models.deletion.CASCADE, related_name='parqueos', to='parqueadero.espacio')),
                ('fkIdVehiculo', models.ForeignKey(db_column='fkIdVehiculo', on_delete=django.db.models.deletion.CASCADE, related_name='parqueos', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Inventario Parqueo',
                'verbose_name_plural': 'Inventario Parqueo',
                'db_table': 'inventario_parqueo',
                'indexes': [models.Index(fields=['parHoraSalida'], name='idx_parqueo_estado')],
            },
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['espNumero'], name='idx_espacio_numero'),
        ),
    ]
