# Generated by Django 6.0.3 on 2026-04-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='espEstado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('RESERVADO', 'Reservado'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=10),
        ),
    ]
