# Generated by Django 6.0.2 on 2026-03-01 16:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehPlaca', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-]+$', 'La placa solo acepta letras, números y guiones')])),
                ('vehTipo', models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto')], default='Carro', max_length=5)),
                ('vehColor', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'El color solo debe contener letras')])),
                ('vehMarca', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\\s]+$', 'La marca solo acepta letras y números')])),
                ('vehModelo', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\\s.\\-]+$', 'El modelo solo acepta letras, números y puntos')])),
                ('vehEstado', models.BooleanField(default=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'El nombre solo debe contener letras')])),
                ('telefono_contacto', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'El teléfono solo debe contener números')])),
                ('fkIdUsuario', models.ForeignKey(blank=True, db_column='fkIdUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
                'indexes': [models.Index(fields=['vehPlaca'], name='idx_vehiculo_placa')],
            },
        ),
    ]
