# Generated by Django 6.0.2 on 2026-02-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehPlaca', models.CharField(max_length=10, unique=True)),
                ('vehTipo', models.CharField(max_length=30)),
                ('vehColor', models.CharField(blank=True, max_length=30)),
                ('vehMarca', models.CharField(blank=True, max_length=50)),
                ('vehModelo', models.CharField(blank=True, max_length=50)),
                ('fkIdUsuario', models.ForeignKey(db_column='fkIdUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
                'indexes': [models.Index(fields=['vehPlaca'], name='idx_vehiculo_placa')],
            },
        ),
    ]
