# Generated by Django 6.0.2 on 2026-02-14 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='es_visitante',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fkIdUsuario',
            field=models.ForeignKey(blank=True, db_column='fkIdUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='usuarios.usuario'),
        ),
    ]
