# Generated by Django 6.0.2 on 2026-02-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehiculo_es_visitante_vehiculo_nombre_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='vehEstado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='vehTipo',
            field=models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto')], default='CARRO', max_length=30),
        ),
    ]
