# Generated by Django 6.0.2 on 2026-02-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_vehiculo_vehestado_alter_vehiculo_vehtipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='vehTipo',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto')], default='Carro', max_length=30),
        ),
    ]
