# Generated by Django 6.0.2 on 2026-02-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuDocumento', models.CharField(max_length=20, unique=True)),
                ('usuNombreCompleto', models.CharField(max_length=150)),
                ('usuCorreo', models.EmailField(max_length=254, unique=True)),
                ('usuTelefono', models.CharField(blank=True, max_length=20)),
                ('usuClaveHash', models.CharField(max_length=255)),
                ('rolTipoRol', models.CharField(choices=[('ADMIN', 'Administrador'), ('VIGILANTE', 'Vigilante'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=10)),
                ('usuEstado', models.BooleanField(default=True)),
                ('usuFechaRegistro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
    ]
