# Generated by Django 6.0.2 on 2026-03-01 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuDocumento', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'El documento solo debe contener números')])),
                ('usuNombre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'El nombre solo debe contener letras')])),
                ('usuApellido', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'El apellido solo debe contener letras')])),
                ('usuCorreo', models.EmailField(max_length=254, unique=True)),
                ('usuTelefono', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'El teléfono solo debe contener números')])),
                ('usuClaveHash', models.CharField(max_length=255)),
                ('rolTipoRol', models.CharField(choices=[('ADMIN', 'Administrador'), ('VIGILANTE', 'Vigilante'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=10)),
                ('usuEstado', models.BooleanField(default=True)),
                ('usuFechaRegistro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
    ]
