# Generated by Django 6.0.3 on 2026-03-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuCorreo',
            field=models.EmailField(max_length=64, unique=True),
        ),
    ]
