# Generated by Django 6.0.3 on 2026-04-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionfidelidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
