# Generated by Django 6.0.3 on 2026-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidad', '0002_alter_configuracionfidelidad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfidelidad',
            name='porcentajeBono',
            field=models.PositiveIntegerField(default=100, help_text='Porcentaje de descuento del bono generado al canjear stickers.'),
        ),
    ]
