# Generated by Django 6.0.2 on 2026-03-01 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueadero', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resFechaReserva', models.DateField()),
                ('resHoraInicio', models.TimeField()),
                ('resHoraFin', models.TimeField(blank=True, null=True)),
                ('resEstado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=10)),
                ('fkIdEspacio', models.ForeignKey(db_column='fkIdEspacio', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='parqueadero.espacio')),
                ('fkIdVehiculo', models.ForeignKey(db_column='fkIdVehiculo', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
            },
        ),
    ]
