# Generated by Django 6.0.2 on 2026-02-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='resConfirmada',
            field=models.BooleanField(default=False),
        ),
    ]
