# Generated by Django 6.0.2 on 2026-02-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_resconfirmada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='resHoraFin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
