# Generated by Django 6.0.2 on 2026-03-01 16:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueadero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precioHora', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'El precio no puede ser negativo')])),
                ('precioHoraVisitante', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'El precio no puede ser negativo')])),
                ('precioDia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'El precio no puede ser negativo')])),
                ('precioMensual', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0, 'El precio no puede ser negativo')])),
                ('activa', models.BooleanField(default=True)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('fkIdTipoEspacio', models.ForeignKey(db_column='fkIdTipoEspacio', on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='parqueadero.tipoespacio')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'db_table': 'tarifas',
            },
        ),
    ]
