# Generated by Django 6.0.2 on 2026-02-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueadero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precioHora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioDia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioMensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activa', models.BooleanField(default=True)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('fkIdTipoEspacio', models.ForeignKey(db_column='fkIdTipoEspacio', on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='parqueadero.tipoespacio')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'db_table': 'tarifas',
            },
        ),
    ]
