# Generated by Django 6.0.2 on 2026-02-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='precioHoraVisitante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
